### PR TITLE
remove extra line break after coloured lines

### PR DESCRIPTION
**Pull request by evilquinn**
suggestion for issue I raised:
https://github.com/leftstick/vscode-gitk/issues/10

### CODE REVIEW

**Comment by evilquinn** [comment]
although, if these line breaks were an intended feature, let me know and I'll try and implement this with the ability to configure it

**Comment by evilquinn** [comment]
um...ignore this for now, for some reason the extension stopped working when I tried to grab screenshot of working output (obviously!).  figuring this out..

**Comment by evilquinn** [comment]
I see this now even after uninstalling/re-installing the extension, no edits from me:

```
mainThreadExtensionService.ts:107 Activating extension 'howardzuo.vscode-gitk' failed: Cannot use import statement outside a module.
$onExtensionActivationError @ mainThreadExtensionService.ts:107
_doInvokeHandler @ rpcProtocol.ts:473
_invokeHandler @ rpcProtocol.ts:458
_receiveRequest @ rpcProtocol.ts:374
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:569
fire @ event.ts:736
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
invoke @ event.ts:569
fire @ event.ts:736
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
(anonymous) @ browserSocketFactory.ts:230
invoke @ event.ts:569
fire @ event.ts:736
_fileReader.onload @ browserSocketFactory.ts:91
```

Not sure what's happening..

**Comment by evilquinn** [comment]
don't understand why the extension broke in the manner mentioned above, I reinstalled previous version, and it works fine.  I was defo using latest version (2.2.1) just a little earlier... #weird

either way, example of detail output with this branch applied:
(very same commit from images in linked issue)
image

**Comment by leftstick** [comment]
great job. Thanks

**Pull request merged**
